### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pshah123** [openai/gpt-2#10]
Hi, is there a license associated with this/any plans towards MIT licensing this model?

**Comment by WuTheFWasThat** [comment]
good question, will get back to you!

**Comment by pshah123** [comment]
From the official blog post:

> We will further publicly discuss this strategy in six months. If you’d like to discuss large language models and their implications, please email us at: languagequestions@openai.com. And if you’re excited about working on cutting-edge language models (and thinking through their policy implications), we’re hiring.

As a follow-up question, is there a possibility of licensing this model under an "ethical" license? i.e. rather than restricting use economically, restricting use ethically. While it doesn't do much to limit illegitimate use, it puts in place some level of legal hindrance which could go a long way in other models as well as to stopping malicious use of AI in the enterprise world.

**Comment by WuTheFWasThat** [comment]
Added MIT license!

@pshah123 we considered "ethical license"-type ideas, but since we wouldn't be able to effectively enforce it (i.e. sue people), we decided to go with plain MIT.  (BTW, it was pointed out that the JSON License has a provision that states: “The Software shall be used for Good, not Evil.”, but that it's probably not effective as a practical matter)

**Comment by reuben** [comment]
@WuTheFWasThat just double checking, did you reach out to authors of pull requests created/merged before the license was added to request their permission to license their contributions under the MIT license terms? I'm asking because this can taint the license of the entire project and cause problems with downstream users, as all contributions made without the license can be assumed to be all rights reserved.

**Comment by WuTheFWasThat** [comment]
thanks for bringing that to my attention, i'll check now

**Comment by xhlulu** [comment]
@WuTheFWasThat Do the weights (1.5B) uploaded on GCP have the same license as the models?

**Comment by WuTheFWasThat** [comment]
yes

**Comment by rosabor** [comment]
Just confirming that GPT-2 can be used commercially like for writing books? Got a bit confused by a blogpost with a legal agreement on the site, but the MIT license sames to say its all good.
