### ISSUE TITLE
Fixing seed and/or setting top_k to 1 don't make sampling deterministic

### ISSUE THREAD

**Issue by WuTheFWasThat** [openai/gpt-2#58]

**Comment by philippHRO** [comment]
`(story_creator) R:\DOCS\DeepLearningStuff\gpt-2-master\src>python interactive_conditional_samples.py --top_k=40 --nsamples=1 --seed=92837923 --length=50
2019-02-20 17:30:23.497353: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Model prompt >>> The quick brown fox jumps over the lazy dog.
======================================== SAMPLE 1 ========================================
 "You're going to have a big time!" he bark, jumping over the dog at a high speed. It seems like he might do the same for you, and so he is. Suddenly he jumps on his hind paws, and the dog wh
================================================================================
Model prompt >>> The quick brown fox jumps over the lazy dog.
======================================== SAMPLE 1 ========================================


"It can walk you up the stairs! Can you ride it?!" The lazy coyote starts moving towards the dog, and the lazy fox jumps up the steps.

The lazy coyote is surprised and then turns around so that the
================================================================================`

**Comment by WuTheFWasThat** [comment]
The seed issue is fixed, as of #65  and #66 

According to https://github.com/openai/gpt-2/issues/27#issuecomment-464750994, top_k=1 is not deterministic though, which is a bug, if true

**Comment by WuTheFWasThat** [comment]
hmm, seems deterministic to me, at least with unconditional samples.  maybe i misread/misremembered
